spring:
  application:
    name: BackEnd
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: fht041029
    url: jdbc:mysql://localhost:3306/fridge_missiondb

mybatis:
  mapper-locations: classpath:com.example.backend.mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

vivo:
  ai:
    app-id: 2025303656       # 从vivo AIGC官网获取
    app-key: kcpnSmTdTrhEHlNy     # 从vivo AIGC官网获取
    model-name: vivo-BlueLM-TB-Pro   # 可选，默认值已在类中设置
    temperature: 0.7                 # 可选，默认值已在类中设置
    max-tokens: 512                  # 可选，默认值已在类中设置
#aliyun:
#  oss:
#    endpoint: https://oss-cn-beijing.aliyuncs.com
#    bucketName: f-java-web01
#    region: cn-beijing